### ISSUE TITLE
Support SSR ?

### ISSUE THREAD

**Issue by isairz** [ktquez/vue-head#21]
```
ReferenceError: document is not defined
    at /Users/isair/Workspace/mus-no-hanazono/node_modules/vue-head/vue-head.js:7:17
    at Object.<anonymous> (/Users/isair/Workspace/mus-no-hanazono/node_modules/vue-head/vue-head.js:259:3)
```

document is not defined in server-side.
Do you have any plan to support ssr?

**Comment by ktquez** [comment]
I will do some tests and will support the "SSR", so available, call here
